"""empty message

Revision ID: 08b567126b8e
Revises: a4341165b314
Create Date: 2020-03-26 20:11:57.279495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08b567126b8e'
down_revision = 'a4341165b314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'dueDate')
    op.drop_column('todo', 'createdDate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('createdDate', mysql.VARCHAR(length=12), nullable=True))
    op.add_column('todo', sa.Column('dueDate', mysql.VARCHAR(length=12), nullable=True))
    # ### end Alembic commands ###
