"""empty message

Revision ID: f558b400dbfa
Revises: 08b567126b8e
Create Date: 2020-03-26 20:12:42.923669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f558b400dbfa'
down_revision = '08b567126b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('createdDate', sa.String(length=25), nullable=True))
    op.add_column('todo', sa.Column('dueDate', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'dueDate')
    op.drop_column('todo', 'createdDate')
    # ### end Alembic commands ###
